version: '3.8'
services:
  mongodb:
    image: mongo:8.0
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mg1234
    ports:
      - "27017:27017"